name: Trigger auto deployment for container-app-gemea2tnwv5uq

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-gemea2tnwv5uq-AutoDeployTrigger-b40d7dac-7d6e-4856-8250-f3ba942d3d28.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPGEMEA2TNWV5UQ_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPGEMEA2TNWV5UQ_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPGEMEA2TNWV5UQ_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: defaultacrcontainerregistrybf72.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPGEMEA2TNWV5UQ_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPGEMEA2TNWV5UQ_REGISTRY_PASSWORD }}
          containerAppName: container-app-gemea2tnwv5uq
          resourceGroup: chatbotreactnodejs87c9aca8
          imageToBuild: defaultacrcontainerregistrybf72.azurecr.io/container-app-gemea2tnwv5uq:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


